### ISSUE TITLE
Change Pool

### ISSUE THREAD

**Issue by tecnoinfoch** [shineangelic/MPW#3]
Hi,

is it possible to insert a pool as desired and not the default ones?
I have created a pool with open-ethereum-pool of sammy007 and I would like to use your app
for my pool.

Thanks

**Comment by shineangelic** [comment]
It's dynamic, once you select one, it will become the "default" and should
be auto-selected the next times you launch it

Alessandro

2018-03-09 8:37 GMT+01:00 tecnoinfoch <notifications@github.com>:

**Comment by tecnoinfoch** [comment]
I badly explained myself
I have a pool called pool.athesis.com how do I insert it?

thanks

Claudio Rossini


------ Messaggio originale ------
Da: "Alessandro Del Pex" <notifications@github.com>
A: "shineangelic/MPW" <MPW@noreply.github.com>
Cc: "tecnoinfoch" <develop@tecnoinfo.ch>; "Author" 
<author@noreply.github.com>
Inviato: 09/03/2018 10:15:31
Oggetto: Re: [shineangelic/MPW] Change Pool (#3)

**Comment by shineangelic** [comment]
*Dolomiti Ethereum Pool* ahahah Grandee!!

Io sono di Conegliano Veneto, è piccolo il mondo :)


il pool te lo devo aggiungere io a mano, dopo aver fatto tutti i test.
Stasera lo faccio.

Alessandro



2018-03-09 10:25 GMT+01:00 tecnoinfoch <notifications@github.com>:

**Comment by tecnoinfoch** [comment]
Ha si proprio piccolo

Mi fa piacere averti "BECCATO"

Grazie

Claudio

------ Messaggio originale ------
Da: "Alessandro Del Pex" <notifications@github.com>
A: "shineangelic/MPW" <MPW@noreply.github.com>
Cc: "tecnoinfoch" <develop@tecnoinfo.ch>; "Author" 
<author@noreply.github.com>
Inviato: 09/03/2018 12:27:43
Oggetto: Re: [shineangelic/MPW] Change Pool (#3)

**Comment by tecnoinfoch** [comment]
Grazie

Claudio

------ Messaggio originale ------
Da: "Alessandro Del Pex" <notifications@github.com>
A: "shineangelic/MPW" <MPW@noreply.github.com>
Cc: "tecnoinfoch" <develop@tecnoinfo.ch>; "Author" 
<author@noreply.github.com>
Inviato: 11/03/2018 21:18:56
Oggetto: [SPAM-LOW] Re: [shineangelic/MPW] Change Pool (#3)

**Comment by tecnoinfoch** [comment]
Ciao Alessandro,

a gennaio 2018 ho creato una crypto (LiraCoin) che sta iniziando a 
muoversi
fornendoti le API saresti in grado di realizzare un portafoglio per 
questa
coin e se si quanto chiedi? (spero poco perché siamo poveri).

Grazie
Claudio Rossini


------ Messaggio originale ------
Da: "Alessandro Del Pex" <notifications@github.com>
A: "shineangelic/MPW" <MPW@noreply.github.com>
Cc: "tecnoinfoch" <develop@tecnoinfo.ch>; "Author" 
<author@noreply.github.com>
Inviato: 09/03/2018 12:27:43
Oggetto: Re: [shineangelic/MPW] Change Pool (#3)
